// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cntvhujpjlzusrwxmkxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNudHZodWpwamx6dXNyd3hta3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMDA2ODcsImV4cCI6MjA2MDg3NjY4N30.sSbg_Sajket4NcDO3W4pYtZZMUQ3NRskw2PcqkcT804";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);